config:
  gcp:project: ${GCP_PROJECT_ID}
  gcp:region: us-central1
  tequity:environment: development
  tequity:databaseTier: db-f1-micro
  tequity:enableBackups: false
  tequity:deletionProtection: false
